SELECT   
FA.FLOORID as FloorID, 
FA.FLOOR as Floor, 
FL.NAME_SHORT as NameShort,  
FL.NAME_LONG as NameLong,  
AF.SCHELEV as SchematicElevation,   
FA.FLOOR_AREA as FloorArea,  
FA.SENSITIVITY as Sensitivity,  
FA.SOURCEDWG as SourceDWG,  
FA.IN_DATE as InDate,  
FA.LAST_USER as LastUser,  
FA.BUILDINGID as BuildingID,  
FA.SITEID as SiteID,  
FA.SHAPE,  
FA.OBJECTID 
FROM dbo.FLOOR_AREA FA INNER JOIN   
dbo.ACTIVE_FLOOR AF ON FA.FLOORID = AF.FLOORID 
INNER JOIN      dbo.FLOOR_LEVEL FL ON AF.FLOOR = FL.FLOOR 
WHERE        (SENSITIVITY <> 'Hidden')