SELECT 
 FP.FLOORID as FloorID,
 FP.FLOOR as Floor,
FL.NAME_SHORT as NameShort, 
FL.NAME_LONG as NameLong, 
AF.SCHELEV as SchematicElevation, 
 FP.FLOOR_AREA as FloorArea,

 FP.SENSITIVITY as Sensitivity,
 FP.SOURCEDWG as SourceDWG,
 FP.IN_DATE as InDate,
 FP.LAST_USER as LastUser,

 FP.BUILDINGID as BuildingID,
 FP.SITEID as SiteID,
 FP.SHAPE,
 FP.OBJECTID
FROM            dbo.FLOOR_POLY FP
INNER JOIN
  dbo.ACTIVE_FLOOR AF ON FP.FLOORID = AF.FLOORID
INNER JOIN
     dbo.FLOOR_LEVEL FL ON AF.FLOOR = FL.FLOOR
WHERE        (SENSITIVITY <> 'Hidden')