SELECT        OBJECTID, SITEID, BUILDINGID, FLOOR, FLOORID, ZONEID, ZONENAME, ZONETYPE, SENSITIVITY, IN_DATE, LAST_USER, SOURCEDWG, GlobalID, SHAPE
FROM            dbo.FLOOR_ZONE
WHERE        (SENSITIVITY <> 'Hidden')