SELECT 
 FLOORID as FloorID,
 FLOOR as Floor,
FL.NAME_SHORT as NameShort, 
FL.NAME_LONG as NameLong, 
AF.SCHELEV as SchematicElevation, 
 FLOOR_AREA as FloorArea,
-- SCHELEV,
-- ALTITUDE,
 SENSITIVITY as Sensitivity,
 SOURCEDWG as SourceDWG,
 IN_DATE as InDate,
 LAST_USER as LastUser,
-- GlobalID,
-- FLOOR_NAME,
-- BLDG_NAME,
 BUILDINGID as BuildingID,
 SITEID as SiteID,
 SHAPE,
 OBJECTID
FROM            dbo.FLOOR_POLY FP
INNER JOIN
  dbo.ACTIVE_FLOOR AF ON FP.FLOORID = AF.FLOORID
INNER JOIN
     dbo.FLOOR_LEVEL FL ON AF.FLOOR = FL.FLOOR
WHERE        (SENSITIVITY <> 'Hidden')