  SELECT        
  SPC.SPACEID AS SpaceID, 
  SPC.ROOM AS Room, 
  SPC.SENSITIVITY AS Sensitivity, 
  SPC.IN_DATE AS InDate, 
  SPC.LAST_USER AS LastUser, 
  SPC.FLOOR AS Floor, 
  AF.SCHELEV AS SchematicElevation, 
  FL.NAME_LONG AS FloorNameLong, 
  FL.NAME_SHORT AS FloorNameShort, 
  SPC.FLOORID AS FloorID, 
  SPC.BUILDINGID AS BuildingID, 
  SPC.SITEID AS SiteID, 
  SPC.SHAPE, 
  SPC.OBJECTID AS ObjectID
FROM dbo.INTERIORSPACE_POINT SPC 
INNER JOIN
     dbo.ACTIVE_FLOOR AF ON SPC.FLOORID = AF.FLOORID 
INNER JOIN
     dbo.FLOOR_LEVEL FL ON AF.FLOOR = FL.FLOOR
WHERE        (SPC.SENSITIVITY <> 'Hidden')