# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# TruncateStagingLoad.py
# Created on: 2014-10-22 15:58:56.00000
#   (generated by ArcGIS/ModelBuilder)
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy


# Local variables:
stg = "C:\\Apps\\Gizinta\\gseUW\\ETL\\serverConfig\\GIS Staging.sde\\UWGISStaging.DBO.Floorplan\\"
Floor_Poly = stg + "UWGISStaging.DBO.Floor_Poly"
FloorplanLine = stg + "UWGISStaging.DBO.FloorplanLine"
InteriorSpace = stg + "UWGISStaging.DBO.InteriorSpace"

# Process: Truncate Table
arcpy.TruncateTable_management(Floor_Poly)

# Process: Truncate Table (2)
arcpy.TruncateTable_management(FloorplanLine)

# Process: Truncate Table (3)
arcpy.TruncateTable_management(InteriorSpace)

