CREATE VIEW dbo.eFloorPageTExceptProduction AS SELECT BUILDINGID,SOURCEID,CALCROT,SHAPE.STAsText() AS SHAPE_TEXT FROM UWCADStaging.dbo.FloorPageTemplate EXCEPT  SELECT BUILDINGID,SOURCEID,CALCROT,SHAPE_TEXT FROM OPENQUERY([maps.uw.edu], 'SELECT BUILDINGID,SOURCEID,CALCROT,SHAPE.STAsText() AS SHAPE_TEXT FROM UWCadSde.dbo.FloorPageTemplate');
GO
CREATE VIEW dbo.eFloorPageTExceptStaging AS  SELECT BUILDINGID,SOURCEID,CALCROT,SHAPE_TEXT FROM OPENQUERY([maps.uw.edu], 'SELECT BUILDINGID,SOURCEID,CALCROT,SHAPE.STAsText() AS SHAPE_TEXT FROM UWCadSde.dbo.FloorPageTemplate') EXCEPT  SELECT BUILDINGID,SOURCEID,CALCROT,SHAPE.STAsText() AS SHAPE_TEXT FROM UWCADStaging.dbo.FloorPageTemplate;
GO
CREATE VIEW dbo.eBuildingExceptProduction AS SELECT SOURCEDWG,BUILDINGID,FACILITYNO,SHAPE.STAsText() AS SHAPE_TEXT FROM UWCADStaging.dbo.Building EXCEPT  SELECT SOURCEDWG,BUILDINGID,FACILITYNO,SHAPE_TEXT FROM OPENQUERY([maps.uw.edu], 'SELECT SOURCEDWG,BUILDINGID,FACILITYNO,SHAPE.STAsText() AS SHAPE_TEXT FROM UWCadSde.dbo.Building');
GO
CREATE VIEW dbo.eBuildingExceptStaging AS  SELECT SOURCEDWG,BUILDINGID,FACILITYNO,SHAPE_TEXT FROM OPENQUERY([maps.uw.edu], 'SELECT SOURCEDWG,BUILDINGID,FACILITYNO,SHAPE.STAsText() AS SHAPE_TEXT FROM UWCadSde.dbo.Building') EXCEPT  SELECT SOURCEDWG,BUILDINGID,FACILITYNO,SHAPE.STAsText() AS SHAPE_TEXT FROM UWCADStaging.dbo.Building;
GO
CREATE VIEW dbo.eBuildingPointExceptProduction AS SELECT BUILDINGID,SOURCEDWG,SHAPE.STAsText() AS SHAPE_TEXT FROM UWCADStaging.dbo.Building_Point EXCEPT  SELECT BUILDINGID,SOURCEDWG,SHAPE_TEXT FROM OPENQUERY([maps.uw.edu], 'SELECT BUILDINGID,SOURCEDWG,SHAPE.STAsText() AS SHAPE_TEXT FROM UWCadSde.dbo.Building_Point');
GO
CREATE VIEW dbo.eBuildingPointExceptStaging AS  SELECT BUILDINGID,SOURCEDWG,SHAPE_TEXT FROM OPENQUERY([maps.uw.edu], 'SELECT BUILDINGID,SOURCEDWG,SHAPE.STAsText() AS SHAPE_TEXT FROM UWCadSde.dbo.Building_Point') EXCEPT  SELECT BUILDINGID,SOURCEDWG,SHAPE.STAsText() AS SHAPE_TEXT FROM UWCADStaging.dbo.Building_Point;
GO
CREATE VIEW dbo.eLandscapeAreaExceptProduction AS SELECT FACILITYID,SURFTYPE,SOURCEID,SOURCEDWG,SHAPE.STAsText() AS SHAPE_TEXT FROM UWCADStaging.dbo.LandscapeArea EXCEPT  SELECT FACILITYID,SURFTYPE,SOURCEID,SOURCEDWG,SHAPE_TEXT FROM OPENQUERY([maps.uw.edu], 'SELECT FACILITYID,SURFTYPE,SOURCEID,SOURCEDWG,SHAPE.STAsText() AS SHAPE_TEXT FROM UWCadSde.dbo.LandscapeArea');
GO
CREATE VIEW dbo.eLandscapeAreaExceptStaging AS  SELECT FACILITYID,SURFTYPE,SOURCEID,SOURCEDWG,SHAPE_TEXT FROM OPENQUERY([maps.uw.edu], 'SELECT FACILITYID,SURFTYPE,SOURCEID,SOURCEDWG,SHAPE.STAsText() AS SHAPE_TEXT FROM UWCadSde.dbo.LandscapeArea') EXCEPT  SELECT FACILITYID,SURFTYPE,SOURCEID,SOURCEDWG,SHAPE.STAsText() AS SHAPE_TEXT FROM UWCADStaging.dbo.LandscapeArea;
GO
CREATE VIEW dbo.eStreetPavementExceptProduction AS SELECT FACILITYID,SURFTYPE,PAVEUSE,SOURCEID,SOURCEDWG,SHAPE.STAsText() AS SHAPE_TEXT FROM UWCADStaging.dbo.StreetPavement EXCEPT  SELECT FACILITYID,SURFTYPE,PAVEUSE,SOURCEID,SOURCEDWG,SHAPE_TEXT FROM OPENQUERY([maps.uw.edu], 'SELECT FACILITYID,SURFTYPE,PAVEUSE,SOURCEID,SOURCEDWG,SHAPE.STAsText() AS SHAPE_TEXT FROM UWCadSde.dbo.StreetPavement');
GO
CREATE VIEW dbo.eStreetPavementExceptStaging AS  SELECT FACILITYID,SURFTYPE,PAVEUSE,SOURCEID,SOURCEDWG,SHAPE_TEXT FROM OPENQUERY([maps.uw.edu], 'SELECT FACILITYID,SURFTYPE,PAVEUSE,SOURCEID,SOURCEDWG,SHAPE.STAsText() AS SHAPE_TEXT FROM UWCadSde.dbo.StreetPavement') EXCEPT  SELECT FACILITYID,SURFTYPE,PAVEUSE,SOURCEID,SOURCEDWG,SHAPE.STAsText() AS SHAPE_TEXT FROM UWCADStaging.dbo.StreetPavement;
GO
CREATE VIEW dbo.eStreetPavementExceptProduction AS SELECT FACILITYID,SURFTYPE,PAVEUSE,SOURCEID,SOURCEDWG,SHAPE.STAsText() AS SHAPE_TEXT FROM UWCADStaging.dbo.StreetPavement EXCEPT  SELECT FACILITYID,SURFTYPE,PAVEUSE,SOURCEID,SOURCEDWG,SHAPE_TEXT FROM OPENQUERY([maps.uw.edu], 'SELECT FACILITYID,SURFTYPE,PAVEUSE,SOURCEID,SOURCEDWG,SHAPE.STAsText() AS SHAPE_TEXT FROM UWCadSde.dbo.StreetPavement');
GO
CREATE VIEW dbo.eStreetPavementExceptStaging AS  SELECT FACILITYID,SURFTYPE,PAVEUSE,SOURCEID,SOURCEDWG,SHAPE_TEXT FROM OPENQUERY([maps.uw.edu], 'SELECT FACILITYID,SURFTYPE,PAVEUSE,SOURCEID,SOURCEDWG,SHAPE.STAsText() AS SHAPE_TEXT FROM UWCadSde.dbo.StreetPavement') EXCEPT  SELECT FACILITYID,SURFTYPE,PAVEUSE,SOURCEID,SOURCEDWG,SHAPE.STAsText() AS SHAPE_TEXT FROM UWCADStaging.dbo.StreetPavement;
GO
CREATE VIEW dbo.eStreetPavementExceptProduction AS SELECT FACILITYID,SURFTYPE,PAVEUSE,SOURCEID,SOURCEDWG,SHAPE.STAsText() AS SHAPE_TEXT FROM UWCADStaging.dbo.StreetPavement EXCEPT  SELECT FACILITYID,SURFTYPE,PAVEUSE,SOURCEID,SOURCEDWG,SHAPE_TEXT FROM OPENQUERY([maps.uw.edu], 'SELECT FACILITYID,SURFTYPE,PAVEUSE,SOURCEID,SOURCEDWG,SHAPE.STAsText() AS SHAPE_TEXT FROM UWCadSde.dbo.StreetPavement');
GO
CREATE VIEW dbo.eStreetPavementExceptStaging AS  SELECT FACILITYID,SURFTYPE,PAVEUSE,SOURCEID,SOURCEDWG,SHAPE_TEXT FROM OPENQUERY([maps.uw.edu], 'SELECT FACILITYID,SURFTYPE,PAVEUSE,SOURCEID,SOURCEDWG,SHAPE.STAsText() AS SHAPE_TEXT FROM UWCadSde.dbo.StreetPavement') EXCEPT  SELECT FACILITYID,SURFTYPE,PAVEUSE,SOURCEID,SOURCEDWG,SHAPE.STAsText() AS SHAPE_TEXT FROM UWCADStaging.dbo.StreetPavement;
GO
CREATE VIEW dbo.eStreetPavementExceptProduction AS SELECT FACILITYID,SURFTYPE,PAVEUSE,SOURCEID,SOURCEDWG,SHAPE.STAsText() AS SHAPE_TEXT FROM UWCADStaging.dbo.StreetPavement EXCEPT  SELECT FACILITYID,SURFTYPE,PAVEUSE,SOURCEID,SOURCEDWG,SHAPE_TEXT FROM OPENQUERY([maps.uw.edu], 'SELECT FACILITYID,SURFTYPE,PAVEUSE,SOURCEID,SOURCEDWG,SHAPE.STAsText() AS SHAPE_TEXT FROM UWCadSde.dbo.StreetPavement');
GO
CREATE VIEW dbo.eStreetPavementExceptStaging AS  SELECT FACILITYID,SURFTYPE,PAVEUSE,SOURCEID,SOURCEDWG,SHAPE_TEXT FROM OPENQUERY([maps.uw.edu], 'SELECT FACILITYID,SURFTYPE,PAVEUSE,SOURCEID,SOURCEDWG,SHAPE.STAsText() AS SHAPE_TEXT FROM UWCadSde.dbo.StreetPavement') EXCEPT  SELECT FACILITYID,SURFTYPE,PAVEUSE,SOURCEID,SOURCEDWG,SHAPE.STAsText() AS SHAPE_TEXT FROM UWCADStaging.dbo.StreetPavement;
GO
CREATE VIEW dbo.eSiteAmenityExceptProduction AS SELECT SOURCEDWG,SOURCEID,AMENTYPE,SHAPE.STAsText() AS SHAPE_TEXT FROM UWCADStaging.dbo.SiteAmenityLine EXCEPT  SELECT SOURCEDWG,SOURCEID,AMENTYPE,SHAPE_TEXT FROM OPENQUERY([maps.uw.edu], 'SELECT SOURCEDWG,SOURCEID,AMENTYPE,SHAPE.STAsText() AS SHAPE_TEXT FROM UWCadSde.dbo.SiteAmenityLine');
GO
CREATE VIEW dbo.eSiteAmenityExceptStaging AS  SELECT SOURCEDWG,SOURCEID,AMENTYPE,SHAPE_TEXT FROM OPENQUERY([maps.uw.edu], 'SELECT SOURCEDWG,SOURCEID,AMENTYPE,SHAPE.STAsText() AS SHAPE_TEXT FROM UWCadSde.dbo.SiteAmenityLine') EXCEPT  SELECT SOURCEDWG,SOURCEID,AMENTYPE,SHAPE.STAsText() AS SHAPE_TEXT FROM UWCADStaging.dbo.SiteAmenityLine;
GO
CREATE VIEW dbo.eWaterbodyExceptProduction AS SELECT NAME,TYPE,SOURCEID,SOURCEDWG,SHAPE.STAsText() AS SHAPE_TEXT FROM UWCADStaging.dbo.Waterbody EXCEPT  SELECT NAME,TYPE,SOURCEID,SOURCEDWG,SHAPE_TEXT FROM OPENQUERY([maps.uw.edu], 'SELECT NAME,TYPE,SOURCEID,SOURCEDWG,SHAPE.STAsText() AS SHAPE_TEXT FROM UWCadSde.dbo.Waterbody');
GO
CREATE VIEW dbo.eWaterbodyExceptStaging AS  SELECT NAME,TYPE,SOURCEID,SOURCEDWG,SHAPE_TEXT FROM OPENQUERY([maps.uw.edu], 'SELECT NAME,TYPE,SOURCEID,SOURCEDWG,SHAPE.STAsText() AS SHAPE_TEXT FROM UWCadSde.dbo.Waterbody') EXCEPT  SELECT NAME,TYPE,SOURCEID,SOURCEDWG,SHAPE.STAsText() AS SHAPE_TEXT FROM UWCADStaging.dbo.Waterbody;
GO
CREATE VIEW dbo.eFloorAreaExceptProduction AS SELECT FLOORID,SOURCEDWG,SHAPE.STAsText() AS SHAPE_TEXT FROM UWCADStaging.dbo.FloorArea EXCEPT  SELECT FLOORID,SOURCEDWG,SHAPE_TEXT FROM OPENQUERY([maps.uw.edu], 'SELECT FLOORID,SOURCEDWG,SHAPE.STAsText() AS SHAPE_TEXT FROM UWCadSde.dbo.FloorArea');
GO
CREATE VIEW dbo.eFloorAreaExceptStaging AS  SELECT FLOORID,SOURCEDWG,SHAPE_TEXT FROM OPENQUERY([maps.uw.edu], 'SELECT FLOORID,SOURCEDWG,SHAPE.STAsText() AS SHAPE_TEXT FROM UWCadSde.dbo.FloorArea') EXCEPT  SELECT FLOORID,SOURCEDWG,SHAPE.STAsText() AS SHAPE_TEXT FROM UWCADStaging.dbo.FloorArea;
GO
CREATE VIEW dbo.eFloorplanLineExceptProduction AS SELECT FLOORID,SOURCELAYER,SOURCEDWG,SHAPE.STAsText() AS SHAPE_TEXT FROM UWCADStaging.dbo.FloorplanLine EXCEPT  SELECT FLOORID,SOURCELAYER,SOURCEDWG,SHAPE_TEXT FROM OPENQUERY([maps.uw.edu], 'SELECT FLOORID,SOURCELAYER,SOURCEDWG,SHAPE.STAsText() AS SHAPE_TEXT FROM UWCadSde.dbo.FloorplanLine');
GO
CREATE VIEW dbo.eFloorplanLineExceptStaging AS  SELECT FLOORID,SOURCELAYER,SOURCEDWG,SHAPE_TEXT FROM OPENQUERY([maps.uw.edu], 'SELECT FLOORID,SOURCELAYER,SOURCEDWG,SHAPE.STAsText() AS SHAPE_TEXT FROM UWCadSde.dbo.FloorplanLine') EXCEPT  SELECT FLOORID,SOURCELAYER,SOURCEDWG,SHAPE.STAsText() AS SHAPE_TEXT FROM UWCADStaging.dbo.FloorplanLine;
GO
CREATE VIEW dbo.eFloorPolyExceptProduction AS SELECT BUILDINGID,FLOORCODE,FLOORID,FLOORAREA,SOURCEID,SOURCEDWG,SHAPE.STAsText() AS SHAPE_TEXT FROM UWCADStaging.dbo.Floor_Poly EXCEPT  SELECT BUILDINGID,FLOORCODE,FLOORID,FLOORAREA,SOURCEID,SOURCEDWG,SHAPE_TEXT FROM OPENQUERY([maps.uw.edu], 'SELECT BUILDINGID,FLOORCODE,FLOORID,FLOORAREA,SOURCEID,SOURCEDWG,SHAPE.STAsText() AS SHAPE_TEXT FROM UWCadSde.dbo.Floor_Poly');
GO
CREATE VIEW dbo.eFloorPolyExceptStaging AS  SELECT BUILDINGID,FLOORCODE,FLOORID,FLOORAREA,SOURCEID,SOURCEDWG,SHAPE_TEXT FROM OPENQUERY([maps.uw.edu], 'SELECT BUILDINGID,FLOORCODE,FLOORID,FLOORAREA,SOURCEID,SOURCEDWG,SHAPE.STAsText() AS SHAPE_TEXT FROM UWCadSde.dbo.Floor_Poly') EXCEPT  SELECT BUILDINGID,FLOORCODE,FLOORID,FLOORAREA,SOURCEID,SOURCEDWG,SHAPE.STAsText() AS SHAPE_TEXT FROM UWCADStaging.dbo.Floor_Poly;
GO
CREATE VIEW dbo.eInteriorSpaceExceptProduction AS SELECT FLOORID,ROOMNUMBER,SPACEID,SPACEAREA,SOURCEID,SHAPE.STAsText() AS SHAPE_TEXT FROM UWCADStaging.dbo.InteriorSpace EXCEPT  SELECT FLOORID,ROOMNUMBER,SPACEID,SPACEAREA,SOURCEID,SHAPE_TEXT FROM OPENQUERY([maps.uw.edu], 'SELECT FLOORID,ROOMNUMBER,SPACEID,SPACEAREA,SOURCEID,SHAPE.STAsText() AS SHAPE_TEXT FROM UWCadSde.dbo.InteriorSpace');
GO
CREATE VIEW dbo.eInteriorSpaceExceptStaging AS  SELECT FLOORID,ROOMNUMBER,SPACEID,SPACEAREA,SOURCEID,SHAPE_TEXT FROM OPENQUERY([maps.uw.edu], 'SELECT FLOORID,ROOMNUMBER,SPACEID,SPACEAREA,SOURCEID,SHAPE.STAsText() AS SHAPE_TEXT FROM UWCadSde.dbo.InteriorSpace') EXCEPT  SELECT FLOORID,ROOMNUMBER,SPACEID,SPACEAREA,SOURCEID,SHAPE.STAsText() AS SHAPE_TEXT FROM UWCADStaging.dbo.InteriorSpace;
GO
CREATE VIEW dbo.eInteriorSpacePointExceptProduction AS SELECT ROOMNUMBER,SPACEID,FLOORID FROM UWCADStaging.dbo.InteriorSpace_Point EXCEPT  SELECT ROOMNUMBER,SPACEID,FLOORID FROM OPENQUERY([maps.uw.edu], 'SELECT ROOMNUMBER,SPACEID,FLOORID FROM UWCadSde.dbo.InteriorSpace_Point');
GO
CREATE VIEW dbo.eInteriorSpacePointExceptStaging AS  SELECT ROOMNUMBER,SPACEID,FLOORID FROM OPENQUERY([maps.uw.edu], 'SELECT ROOMNUMBER,SPACEID,FLOORID FROM UWCadSde.dbo.InteriorSpace_Point') EXCEPT  SELECT ROOMNUMBER,SPACEID,FLOORID FROM UWCADStaging.dbo.InteriorSpace_Point;
GO
CREATE VIEW dbo.eInteriorSpaceIsoExceptProduction AS SELECT BUILDINGID,FLOORCODE,FLOORID,ROOMNUMBER,SPACEID,SHAPE.STAsText() AS SHAPE_TEXT FROM UWCADStaging.dbo.InteriorSpace_Isometric EXCEPT  SELECT BUILDINGID,FLOORCODE,FLOORID,ROOMNUMBER,SPACEID,SHAPE_TEXT FROM OPENQUERY([maps.uw.edu], 'SELECT BUILDINGID,FLOORCODE,FLOORID,ROOMNUMBER,SPACEID,SHAPE.STAsText() AS SHAPE_TEXT FROM UWCadSde.dbo.InteriorSpace_Isometric');
GO
CREATE VIEW dbo.eInteriorSpaceIsoExceptStaging AS  SELECT BUILDINGID,FLOORCODE,FLOORID,ROOMNUMBER,SPACEID,SHAPE_TEXT FROM OPENQUERY([maps.uw.edu], 'SELECT BUILDINGID,FLOORCODE,FLOORID,ROOMNUMBER,SPACEID,SHAPE.STAsText() AS SHAPE_TEXT FROM UWCadSde.dbo.InteriorSpace_Isometric') EXCEPT  SELECT BUILDINGID,FLOORCODE,FLOORID,ROOMNUMBER,SPACEID,SHAPE.STAsText() AS SHAPE_TEXT FROM UWCADStaging.dbo.InteriorSpace_Isometric;
GO
CREATE VIEW dbo.eFloorplanLineIsoExceptProduction AS SELECT FLOORID,SOURCELAYER,SOURCEDWG,SHAPE.STAsText() AS SHAPE_TEXT FROM UWCADStaging.dbo.FloorplanLine_Isometric EXCEPT  SELECT FLOORID,SOURCELAYER,SOURCEDWG,SHAPE_TEXT FROM OPENQUERY([maps.uw.edu], 'SELECT FLOORID,SOURCELAYER,SOURCEDWG,SHAPE.STAsText() AS SHAPE_TEXT FROM UWCadSde.dbo.FloorplanLine_Isometric');
GO
CREATE VIEW dbo.eFloorplanLineIsoExceptStaging AS  SELECT FLOORID,SOURCELAYER,SOURCEDWG,SHAPE_TEXT FROM OPENQUERY([maps.uw.edu], 'SELECT FLOORID,SOURCELAYER,SOURCEDWG,SHAPE.STAsText() AS SHAPE_TEXT FROM UWCadSde.dbo.FloorplanLine_Isometric') EXCEPT  SELECT FLOORID,SOURCELAYER,SOURCEDWG,SHAPE.STAsText() AS SHAPE_TEXT FROM UWCADStaging.dbo.FloorplanLine_Isometric;
GO
CREATE VIEW dbo.eFloorAreaIsoExceptProduction AS SELECT FLOORID,SOURCEDWG,SHAPE.STAsText() AS SHAPE_TEXT FROM UWCADStaging.dbo.FloorArea_Isometric EXCEPT  SELECT FLOORID,SOURCEDWG,SHAPE_TEXT FROM OPENQUERY([maps.uw.edu], 'SELECT FLOORID,SOURCEDWG,SHAPE.STAsText() AS SHAPE_TEXT FROM UWCadSde.dbo.FloorArea_Isometric');
GO
CREATE VIEW dbo.eFloorAreaIsoExceptStaging AS  SELECT FLOORID,SOURCEDWG,SHAPE_TEXT FROM OPENQUERY([maps.uw.edu], 'SELECT FLOORID,SOURCEDWG,SHAPE.STAsText() AS SHAPE_TEXT FROM UWCadSde.dbo.FloorArea_Isometric') EXCEPT  SELECT FLOORID,SOURCEDWG,SHAPE.STAsText() AS SHAPE_TEXT FROM UWCADStaging.dbo.FloorArea_Isometric;
GO
CREATE VIEW dbo.eDoorPointExceptProd AS SELECT FLOORID,SHAPE.STAsText() AS SHAPE_TEXT FROM UWCADStaging.dbo.RT_DoorPoint EXCEPT  SELECT FLOORID,SHAPE_TEXT FROM OPENQUERY([maps.uw.edu], 'SELECT FLOORID,SHAPE.STAsText() AS SHAPE_TEXT FROM UWCadSde.dbo.RT_DoorPoint');
GO
CREATE VIEW dbo.eDoorPointStaging AS  SELECT FLOORID,SHAPE_TEXT FROM OPENQUERY([maps.uw.edu], 'SELECT FLOORID,SHAPE.STAsText() AS SHAPE_TEXT FROM UWCadSde.dbo.RT_DoorPoint') EXCEPT  SELECT FLOORID,SHAPE.STAsText() AS SHAPE_TEXT FROM UWCADStaging.dbo.RT_DoorPoint;
GO
CREATE VIEW dbo.eStopProd AS SELECT FLOORID,SPACEID1,SPACEID2,SHAPE.STAsText() AS SHAPE_TEXT FROM UWCADStaging.dbo.RT_Stop EXCEPT  SELECT FLOORID,SPACEID1,SPACEID2,SHAPE_TEXT FROM OPENQUERY([maps.uw.edu], 'SELECT FLOORID,SPACEID1,SPACEID2,SHAPE.STAsText() AS SHAPE_TEXT FROM UWCadSde.dbo.RT_Stop');
GO
CREATE VIEW dbo.eStopStaging AS  SELECT FLOORID,SPACEID1,SPACEID2,SHAPE_TEXT FROM OPENQUERY([maps.uw.edu], 'SELECT FLOORID,SPACEID1,SPACEID2,SHAPE.STAsText() AS SHAPE_TEXT FROM UWCadSde.dbo.RT_Stop') EXCEPT  SELECT FLOORID,SPACEID1,SPACEID2,SHAPE.STAsText() AS SHAPE_TEXT FROM UWCADStaging.dbo.RT_Stop;
GO
CREATE VIEW dbo.eRoomPointProd AS SELECT FLOORID,SPACEID,ADA,SHAPE.STAsText() AS SHAPE_TEXT FROM UWCADStaging.dbo.RT_RoomPoint EXCEPT  SELECT FLOORID,SPACEID,ADA,SHAPE_TEXT FROM OPENQUERY([maps.uw.edu], 'SELECT FLOORID,SPACEID,ADA,SHAPE.STAsText() AS SHAPE_TEXT FROM UWCadSde.dbo.RT_RoomPoint');
GO
CREATE VIEW dbo.eRoomPointStaging AS  SELECT FLOORID,SPACEID,ADA,SHAPE_TEXT FROM OPENQUERY([maps.uw.edu], 'SELECT FLOORID,SPACEID,ADA,SHAPE.STAsText() AS SHAPE_TEXT FROM UWCadSde.dbo.RT_RoomPoint') EXCEPT  SELECT FLOORID,SPACEID,ADA,SHAPE.STAsText() AS SHAPE_TEXT FROM UWCADStaging.dbo.RT_RoomPoint;
GO
CREATE VIEW dbo.eLineInteriorProd AS SELECT FLOORID,SPACEID,ADA,SHAPE.STAsText() AS SHAPE_TEXT,FROMFLOOR,TOFLOOR FROM UWCADStaging.dbo.RT_LineInterior EXCEPT  SELECT FLOORID,SPACEID,ADA,SHAPE_TEXT,FROMFLOOR,TOFLOOR FROM OPENQUERY([maps.uw.edu], 'SELECT FLOORID,SPACEID,ADA,SHAPE.STAsText() AS SHAPE_TEXT,FROMFLOOR,TOFLOOR FROM UWCadSde.dbo.RT_LineInterior');
GO
CREATE VIEW dbo.eLineInteriorStaging AS  SELECT FLOORID,SPACEID,ADA,SHAPE_TEXT,FROMFLOOR,TOFLOOR FROM OPENQUERY([maps.uw.edu], 'SELECT FLOORID,SPACEID,ADA,SHAPE.STAsText() AS SHAPE_TEXT,FROMFLOOR,TOFLOOR FROM UWCadSde.dbo.RT_LineInterior') EXCEPT  SELECT FLOORID,SPACEID,ADA,SHAPE.STAsText() AS SHAPE_TEXT,FROMFLOOR,TOFLOOR FROM UWCADStaging.dbo.RT_LineInterior;
GO
CREATE VIEW dbo.eLineRmConnectorProd AS SELECT FLOORID,SPACEID,ADA,SHAPE.STAsText() AS SHAPE_TEXT,FROMFLOOR,TOFLOOR FROM UWCADStaging.dbo.RT_LineRmConnector EXCEPT  SELECT FLOORID,SPACEID,ADA,SHAPE_TEXT,FROMFLOOR,TOFLOOR FROM OPENQUERY([maps.uw.edu], 'SELECT FLOORID,SPACEID,ADA,SHAPE.STAsText() AS SHAPE_TEXT,FROMFLOOR,TOFLOOR FROM UWCadSde.dbo.RT_LineRmConnector');
GO
CREATE VIEW dbo.eLineRmConnectorStaging AS  SELECT FLOORID,SPACEID,ADA,SHAPE_TEXT,FROMFLOOR,TOFLOOR FROM OPENQUERY([maps.uw.edu], 'SELECT FLOORID,SPACEID,ADA,SHAPE.STAsText() AS SHAPE_TEXT,FROMFLOOR,TOFLOOR FROM UWCadSde.dbo.RT_LineRmConnector') EXCEPT  SELECT FLOORID,SPACEID,ADA,SHAPE.STAsText() AS SHAPE_TEXT,FROMFLOOR,TOFLOOR FROM UWCADStaging.dbo.RT_LineRmConnector;
GO
CREATE VIEW dbo.eLineTransitionProd AS SELECT FLOORID,SPACEID,ADA,SHAPE.STAsText() AS SHAPE_TEXT,FROMFLOOR,TOFLOOR FROM UWCADStaging.dbo.RT_LineTransition EXCEPT  SELECT FLOORID,SPACEID,ADA,SHAPE_TEXT,FROMFLOOR,TOFLOOR FROM OPENQUERY([maps.uw.edu], 'SELECT FLOORID,SPACEID,ADA,SHAPE.STAsText() AS SHAPE_TEXT,FROMFLOOR,TOFLOOR FROM UWCadSde.dbo.RT_LineTransition');
GO
CREATE VIEW dbo.eLineTransitionStaging AS  SELECT FLOORID,SPACEID,ADA,SHAPE_TEXT,FROMFLOOR,TOFLOOR FROM OPENQUERY([maps.uw.edu], 'SELECT FLOORID,SPACEID,ADA,SHAPE.STAsText() AS SHAPE_TEXT,FROMFLOOR,TOFLOOR FROM UWCadSde.dbo.RT_LineTransition') EXCEPT  SELECT FLOORID,SPACEID,ADA,SHAPE.STAsText() AS SHAPE_TEXT,FROMFLOOR,TOFLOOR FROM UWCADStaging.dbo.RT_LineTransition;
GO
CREATE VIEW dbo.eWaypointProd AS SELECT FLOORID,NAME,WAYPOINTTYPE,SHAPE.STAsText() AS SHAPE_TEXT FROM UWCADStaging.dbo.RT_Waypoint EXCEPT  SELECT FLOORID,NAME,WAYPOINTTYPE,SHAPE_TEXT FROM OPENQUERY([maps.uw.edu], 'SELECT FLOORID,NAME,WAYPOINTTYPE,SHAPE.STAsText() AS SHAPE_TEXT FROM UWCadSde.dbo.RT_Waypoint');
GO
CREATE VIEW dbo.eWaypointStaging AS  SELECT FLOORID,NAME,WAYPOINTTYPE,SHAPE_TEXT FROM OPENQUERY([maps.uw.edu], 'SELECT FLOORID,NAME,WAYPOINTTYPE,SHAPE.STAsText() AS SHAPE_TEXT FROM UWCadSde.dbo.RT_Waypoint') EXCEPT  SELECT FLOORID,NAME,WAYPOINTTYPE,SHAPE.STAsText() AS SHAPE_TEXT FROM UWCADStaging.dbo.RT_Waypoint;
GO
