call F:\Vault_Mirror\Vault_Mirror_Partial.bat
call C:\apps\Gizinta\gseUW\ETL\Incremental_XP_RT_update_ARZ.bat
call C:\apps\Gizinta\gseUW\ETL\Incremental_XP_RT_update_BBC.bat
call C:\apps\Gizinta\gseUW\ETL\Incremental_XP_RT_update_FHL.bat
call C:\apps\Gizinta\gseUW\ETL\Incremental_XP_RT_update_HMC.bat
call C:\apps\Gizinta\gseUW\ETL\Incremental_XP_RT_update_PAF.bat
call C:\apps\Gizinta\gseUW\ETL\Incremental_XP_RT_update_SEM.bat
call C:\apps\Gizinta\gseUW\ETL\Incremental_XP_RT_update_SLU.bat
call C:\apps\Gizinta\gseUW\ETL\Incremental_XP_RT_update_SOT.bat
call C:\apps\Gizinta\gseUW\ETL\Incremental_XP_RT_update_SPT.bat
call C:\apps\Gizinta\gseUW\ETL\Incremental_XP_RT_update_UWB.bat
call C:\apps\Gizinta\gseUW\ETL\Incremental_XP_RT_update_UWS.bat
call C:\apps\Gizinta\gseUW\ETL\Incremental_XP_RT_update_UWT.bat