call C:\Apps\Gizinta\gseUW\ETL\load_ARZ.bat
call C:\Apps\Gizinta\gseUW\ETL\load_BBC.bat
call C:\Apps\Gizinta\gseUW\ETL\load_FHL.bat
call C:\Apps\Gizinta\gseUW\ETL\load_HMC.bat
call C:\Apps\Gizinta\gseUW\ETL\load_ITL.bat
call C:\Apps\Gizinta\gseUW\ETL\load_PAF.bat
call C:\Apps\Gizinta\gseUW\ETL\load_SEM.bat
call C:\Apps\Gizinta\gseUW\ETL\load_SLU.bat
call C:\Apps\Gizinta\gseUW\ETL\load_SOT.bat
call C:\Apps\Gizinta\gseUW\ETL\load_SPT.bat
call C:\Apps\Gizinta\gseUW\ETL\load_UWB.bat
call C:\Apps\Gizinta\gseUW\ETL\load_UWS.bat
call C:\Apps\Gizinta\gseUW\ETL\load_UWT.bat
call C:\Apps\Gizinta\gseUW\ETL\load_WAS.bat
