# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# buildNDS.py
# Created on: 2015-03-18 12:03:10.00000
#   (generated by ArcGIS/ModelBuilder)
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy, time

# Check out any necessary licenses
arcpy.CheckOutExtension("Network")

Navigation_ND = "C:\\apps\\Gizinta\\gseUW\\ETL\\batch\\Routing\\Routing.gdb\\Navigation\\Navigation_ND"
# Process: Build Network
print time.strftime("%Y-%m-%d %H:%M:%S", time.localtime())
print 'Building network'
arcpy.BuildNetwork_na(Navigation_ND)
print time.strftime("%Y-%m-%d %H:%M:%S", time.localtime())
print 'Complete'
