# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# updateNDS.py
# Created on: 2015-03-18 12:03:10.00000
#   (generated by ArcGIS/ModelBuilder)
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy

# Check out any necessary licenses
arcpy.CheckOutExtension("Network")

arcpy.env.overwriteOutput = True

# Local variables:
Routing = "C:\\apps\\Gizinta\\gseUW\\ETL\\batch\\Routing"
Navigation = "C:\\apps\\Gizinta\\gseUW\\ETL\\batch\\Routing\\Routing.gdb\\Navigation"
Navigation_1 = "C:\\apps\\Gizinta\\gseUW\\ETL\\batch\\Routing\\Routing_1.gdb\\Navigation"

Navigation_ND = "C:\\apps\\Gizinta\\gseUW\\ETL\\batch\\Routing\\Routing.gdb\\Navigation\\Navigation_ND"

# Process: Create File GDB
print 'Creating File GDB'
arcpy.CreateFileGDB_management(Routing, "Routing_1", "CURRENT")

# Process: Copy
print 'Copying data for Navigation feature dataset'
arcpy.Copy_management(Navigation, Navigation_1, "FeatureDataset")

# Process: Delete Original
print 'Deleting original feature dataset'
arcpy.Delete_management(Navigation)

# Process: Copy
print 'Copying back to original'
arcpy.Copy_management(Navigation_1, Navigation, "FeatureDataset")

# Process: Delete temp
print 'Deleting temporary file gdb'
arcpy.Delete_management(Navigation_1)

print 'Complete'
