# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# setSensitivity.py
# Created on: 2014-10-09 10:40:03.00000
#   (generated by ArcGIS/ModelBuilder)
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy


# Local variables:
datasets = []
WS = "C:\\apps\\Gizinta\\gseUW\\ETL\\serverConfig\\GIS Staging.sde"
datasets.append(WS + "\\UWGIS_Staging.DBO.Floor_Outline")
datasets.append(WS + "\\UWGIS_Staging.DBO.Floor_Point")
datasets.append(WS + "\\UWGIS_Staging.DBO.Floor_Poly")
datasets.append(WS + "\\UWGIS_Staging.DBO.Floor_Zone")
datasets.append(WS + "\\UWGIS_Staging.DBO.FloorplanLine")
datasets.append(WS + "\\UWGIS_Staging.DBO.FloorplanLine_Publish")
datasets.append(WS + "\\UWGIS_Staging.DBO.InteriorSpace")
datasets.append(WS + "\\UWGIS_Staging.DBO.InteriorSpace_Point")
datasets.append(WS + "\\UWGIS_Staging.DBO.InteriorSpace_Tilt")

# 'Hidden' if "BUILDINGID"[4:] in ('1212',  '1053',  '6327') else 'None'

# Process: Calculate Field
for ds in datasets:
	print 'Working on ' + ds
	arcpy.CalculateField_management(ds, "SENSITIVITY", "'Hidden' if !BUILDINGID![4:] in ('1212',  '1053',  '6327') else 'None'", "PYTHON_9.3", "")

